markdown: kramdown
highlighter: rouge
rouge: true
encoding: UTF-8
excerpt_separator: ""
safe: false
future: true

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

permalink: /:year/:month/:title/

name: Steve's Space
tag: satisfying your stevesspace.com needs for over a millenia
url: http://stevesspace.com
github-url: https://github.com/xwipeoutx
twitter-handle: xwipeoutx
avatar-url: /images/steve.jpeg

top-menu:
  - url: /
    text: Home
  - url: /projects
    text: Projects
  - url: /archive
    text: Archive
  - url: /about-me
    text: About Me